// test-vue/src/components/Rect.vue
<script setup lang="ts">
  const props = defineProps<{rectsSize: number}>();
</script>

<template>
    <div class="rect" :style="{width: `${props.rectsSize}px`, height:`${props.rectsSize}px`}"></div>
  </template>
  
  <style scoped>
  .rect {
    border: 1px solid white;
    background-color: var(--baseColor);
}
  </style>

// test-react/src/components/Rect/index.tsx
import "./rectStyles.css";

const Rect = ({rectsSize}: {backgroundColor: string; rectsSize: number}) => {
  return (
    <div
      className="rect"
      style={{width: `${rectsSize}px`, height: `${rectsSize}px`}}
      // style={{backgroundColor: backgroundColor}}
    />
  );
};

export default Rect;
