// test-angular/src/app/micro-components/micro-components.component.ts
import { Component, NgZone, OnInit } from '@angular/core';
import { RenderPlanComponent } from '../render-plan/render-plan.component';
import { FormsModule } from '@angular/forms';
import { CommonModule, NgIf } from '@angular/common';
import { BehaviorSubject, Observable, Observer, Subject, map, of, takeUntil, timer } from 'rxjs';
import { HeaderComponent } from '../header/header.component';

@Component({
  selector: 'app-micro-components',
  standalone: true,
  imports: [RenderPlanComponent, FormsModule, NgIf, CommonModule, HeaderComponent],
  templateUrl: './micro-components.component.html',
  styleUrl: './micro-components.component.css'
})
export class MicroComponentsComponent {
  rectsCount: number = 100;
  rectsSize: number = 5;
  isRendering: boolean = false;
  // isRendering$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);

  timeRender: number = 0;
  finishRender: boolean = false;
  rects: any[] = [];
  startTime: number = 0;
  endTime: number = 0;
  reset: boolean = false;

  private readonly destroy$: Subject<void> = new Subject<void>();

  startRenderRects(): void {
    let _rects = [];
    for (let i = 0; i < this.rectsCount; i++) {
      const backgroundColor = this.generateRandomColor();
      _rects.push({id: i, backgroundColor});
    }
    this.rects = _rects;
    this.isRendering = true;

    // this.isRendering$.next(true);
    this.startTime = performance.now();
    console.log("start: ", performance.now())
  }

  resetTest(): void {
    this.isRendering = false;
    this.finishRender = false;
    this.endTime = 0
    this.startTime = 0;
    this.rects = []
    this.reset = !this.reset;
  }

  setFinishRender($event: number): void {
    setTimeout(() => {
      this.endTime = performance.now()
      console.log(performance.now())
  }, 0);
  }
  generateRandomColor(): string {
    return "#" + Math.floor(Math.random() * 16777215).toString(16);
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}


<div class="micro-components">
    <app-header title="Micro components render test" message="Test polega na mierzeniu czasu renderowania się mikro komponentów w dowolnej ilości."/>
    <div class="options-container">
      <input type="number" [(ngModel)]="rectsCount" placeholder="Podaj ilość komponentów" />
      <input type="number" [(ngModel)]="rectsSize" placeholder="Podaj rozmiar komponentów" />
      <button class="render-button" (click)="startRenderRects()">Render</button>
      <button class="reset-button" (click)="resetTest()">Reset</button>
    </div>
    <div class="render-time">
      <div *ngIf="endTime">
        Czas renderowania: {{ ((endTime - startTime) / 1000).toFixed(4) }} s
      </div>
      <div *ngIf="endTime">
      |  one rect render time {{ ((endTime - startTime) / rectsCount / 1000).toFixed(5) }} s
      </div>
    </div>

    <app-render-plan
      [isRendering]="isRendering"
      [timeRender]="timeRender"
      [countRenderRects]="rectsCount"
      [rects]="rects"
      [rectsSize]="rectsSize"
      (setFinishRender)="setFinishRender($event)"
    ></app-render-plan>
  </div>

// test-react/src/pages/MicroComponents/index.tsx
import {useEffect, useState} from "react";
import RenderPlan from "../../components/RenderPlan";
import {Header} from "../../components/Header";
import "./microComponents.css";

function MicroComponents() {
  const [rectsCount, setRectsCount] = useState(10000);
  const [rectsSize, setRectsSize] = useState(5);

  const [isRendering, setIsRendering] = useState(false);
  const [timeRender, setTimeRender] = useState(0);
  const [countRenderRects, setCountRenderRects] = useState(0);
  const [finishRender, setFinishRender] = useState(false);
  const [rects, setRects] = useState<any>([]);
  const [startTime, setStartTime] = useState(0);
  const [endTime, setEndTime] = useState(0);
  const [reset, setReset] = useState(false);

  // useEffect(() => {
  //   let _rects = [];
  //   for (let i = 0; i < rectsCount; i++) {
  //     const generateRandomColor = () => {
  //       const randomColor =
  //         "#" + Math.floor(Math.random() * 16777215).toString(16);
  //       return randomColor;
  //     };
  //     const backgroundColor = generateRandomColor();
  //     _rects.push({id: i, backgroundColor});
  //     // setCountRenderRects(countRenderRects + 1);
  //   }

  //   setRects(_rects);
  // }, [reset]);

  // useEffect(() => {
  //   if (finishRender) {
  //     setEndTime(performance.now());
  //   }
  // }, [finishRender]);

  const startRenderRects = () => {
    // resetTest();
    setRects([]);
    setIsRendering(false);
    setStartTime(0);
    setEndTime(0);

    setTimeout(() => {
      let _rects = [];

      for (let i = 0; i < rectsCount; i++) {
        const generateRandomColor = () => {
          const randomColor =
            "#" + Math.floor(Math.random() * 16777215).toString(16);
          return randomColor;
        };
        const backgroundColor = generateRandomColor();
        _rects.push({id: i, backgroundColor});
        // setCountRenderRects(countRenderRects + 1);
      }

      setRects(_rects);
      setIsRendering(true);
      setStartTime(performance.now());
      console.log("start: ", performance.now());
    }, 0);
  };

  const resetTest = () => {
    setIsRendering(false);
    setFinishRender(false);
    setStartTime(0);
    setEndTime(0);
  };

  const finishRendering = () => {
    console.log("end: ", performance.now());
    setEndTime(performance.now());
  };

  return (
    <div className="micro-components">
      <Header
        header="Micro components test"
        title="Test polega na mierzeniu czasu renderowania się mikro komponentów w dowolnej ilości. "
      />

      <div className="render-options">
        <input
          type="number"
          value={rectsCount}
          onChange={(text) => setRectsCount(parseInt(text.target.value))}
          placeholder="Podaj ilość komponentów"
        />
        <input
          type="number"
          value={rectsSize}
          onChange={(text) => setRectsSize(parseInt(text.target.value))}
          placeholder="Podaj rozmiar komponentów"
        />
        <button className="render-button" onClick={startRenderRects}>
          Render
        </button>
        <button className="reset-button" onClick={resetTest}>
          Reset
        </button>
      </div>
      <div className="render-time">
        {timeRender !== null && endTime && (
          <div>
            Czas renderowania: {((endTime - startTime) / 1000).toFixed(4)} s
          </div>
        )}
        | {rectsCount} small rects
        <div>
          {" "}
          | one rect render time{" "}
          {((endTime - startTime) / rectsCount / 1000).toFixed(5)} s
        </div>
      </div>
      {isRendering && (
        <RenderPlan
          isRendering={isRendering}
          setTimeRender={setTimeRender}
          timeRender={timeRender}
          countRenderRects={countRenderRects}
          setFinishRender={finishRendering}
          rectsSize={rectsSize}
          rects={rects}
        />
      )}
    </div>
  );
}

export default MicroComponents;
