// test-react/src/pages/FibGenerator/index.tsx
import {useState} from "react";
import {Header} from "../../components/Header";
import "./fibGenStyles.css";

const FibGenerator = () => {
  const [fibonacciSequence, setFibonacciSequence] = useState<any>([]);
  const [loadingTime, setLoadingTime] = useState<any>(null);
  const [isCalculating, setIsCalculating] = useState<any>(false);
  const [count, setCount] = useState(10);

  const generateFibonacciSequence = () => {
    const startTime = performance.now();
    setIsCalculating(true);

    let fib1 = 0,
      fib2 = 1;
    const sequence = [fib1.toString(), fib2.toString()];

    for (let i = 2; i < count; i++) {
      const nextFib = fib1 + fib2;
      sequence.push(nextFib.toString());
      fib1 = fib2;
      fib2 = nextFib;
    }

    const endTime = performance.now();
    const loadTime = endTime - startTime;

    setFibonacciSequence(sequence);
    setLoadingTime(loadTime);
    setIsCalculating(false);
  };

  const handleReset = () => {
    setFibonacciSequence([]);
    setLoadingTime(null);
  };

  return (
    <div className="fib-generator">
      <Header
        header="Generation of a fiboonati sequence"
        title="Test polega na wyliczaniu kolejnych wyrazów ciągu fibonacciego i mierzeniu czasu."
      />
      <div className="render-options">
        <label htmlFor="countInput">Ilość liczb:</label>
        <input
          type="number"
          id="countInput"
          value={count}
          onChange={(e) => setCount(parseInt(e.target.value))}
        />
        <button
          className="render-button"
          disabled={isCalculating}
          onClick={generateFibonacciSequence}
        >
          Start
        </button>
        <button
          className="reset-button"
          disabled={isCalculating}
          onClick={handleReset}
        >
          Reset
        </button>
      </div>
      <div className="render-time">
        <p>
          {loadingTime !== null &&
            `Czas generowania: ${loadingTime.toFixed(2)} ms`}
        </p>
      </div>
      <div className="fib-numbers-container">
        {fibonacciSequence.length > 0 &&
          fibonacciSequence.map((number: string, index: number) => (
            <p className="fib-number" key={index}>
              {number}
            </p>
          ))}
      </div>
    </div>
  );
};

export default FibGenerator;

// test-angular/src/app/fib-generator/fib-generator.component.ts
import { NgFor, NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule, NgModel } from '@angular/forms';
import { HeaderComponent } from '../header/header.component';

@Component({
  selector: 'app-fib-generator',
  standalone: true,
  imports: [NgFor, NgIf, FormsModule, HeaderComponent],
  templateUrl: './fib-generator.component.html',
  styleUrl: './fib-generator.component.css'
})
export class FibGeneratorComponent {
  fibonacciSequence: (number | string)[] = [];
  loadingTime: number | null = null;
  startTime: number = 0;
  isCalculating: boolean = false;
  count: number = 10; 

  constructor() { }

  generateFibonacciSequence() {
    this.startTime = performance.now();
    this.isCalculating = true;

    let fib1 = 0, fib2 = 1;
    this.fibonacciSequence = [fib1, fib2];

    for (let i = 2; i < this.count; i++) {
      const nextFib = fib1 + fib2;
      this.fibonacciSequence.push(nextFib.toString());
      fib1 = fib2;
      fib2 = nextFib;
    }

    const endTime = performance.now();
    const loadTime = endTime - this.startTime;
    this.loadingTime = loadTime;
    this.isCalculating = false;
  }

  handleReset() {
    this.fibonacciSequence = [];
    this.loadingTime = null;
  }
}

<div class="fib-generator">
    <app-header title="Generation of a fiboonati sequence" message="Test polega na wyliczaniu kolejnych wyrazów ciągu fibonacciego i mierzeniu czasu."/>

    <div class="render-options">
      <label for="countInput">Ilość liczb:</label>
      <input type="number" id="countInput" [(ngModel)]="count">
      <button class="render-button" [disabled]="isCalculating" (click)="generateFibonacciSequence()">Start</button>
      <button class="reset-button" [disabled]="isCalculating" (click)="handleReset()">Reset</button>
    </div>
    <div class="render-time">
      <p *ngIf="loadingTime">Czas generowania: {{ loadingTime.toFixed(2) }} ms</p>
    </div>
    <div class="fib-numbers-container" *ngIf="fibonacciSequence.length > 0">
      <p class="fib-number" *ngFor="let number of fibonacciSequence">{{ number }}</p>
    </div>
  </div>
